// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AddProcessReportRequest
    {
        /// <summary>
        /// Initializes a new instance of the AddProcessReportRequest class.
        /// </summary>
        public AddProcessReportRequest() { }

        /// <summary>
        /// Initializes a new instance of the AddProcessReportRequest class.
        /// </summary>
        public AddProcessReportRequest(IList<ProcessReport> processesReport = default(IList<ProcessReport>))
        {
            ProcessesReport = processesReport;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processesReport")]
        public IList<ProcessReport> ProcessesReport { get; set; }

    }
}
