// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public partial class AppCategoryRequest
    {
        /// <summary>
        /// Initializes a new instance of the AppCategoryRequest class.
        /// </summary>
        public AppCategoryRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the AppCategoryRequest class.
        /// </summary>
        public AppCategoryRequest(int? appid = default(int?), string appname = default(string),
            int? categoryid = default(int?), string isactive = default(string))
        {
            Appid = appid;
            Appname = appname;
            Categoryid = categoryid;
            Isactive = isactive;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appid")]
        public int? Appid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appname")]
        public string Appname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryid")]
        public int? Categoryid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }
    }
}