// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class CategoryResponse
    {
        /// <summary>
        ///     Initializes a new instance of the CategoryResponse class.
        /// </summary>
        public CategoryResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the CategoryResponse class.
        /// </summary>
        public CategoryResponse(int? categoryid = default, string categoryname = default,
            string createdby = default, DateTime? creationdate = default,
            string isactive = default, DateTime? lastupdate = default,
            string updateby = default)
        {
            Categoryid = categoryid;
            Categoryname = categoryname;
            Createdby = createdby;
            Creationdate = creationdate;
            Isactive = isactive;
            Lastupdate = lastupdate;
            Updateby = updateby;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryid")]
        public int? Categoryid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryname")]
        public string Categoryname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdby")]
        public string Createdby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creationdate")]
        public DateTime? Creationdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastupdate")]
        public DateTime? Lastupdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateby")]
        public string Updateby { get; set; }
    }
}