// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CategoryRequest
    {
        /// <summary>
        /// Initializes a new instance of the CategoryRequest class.
        /// </summary>
        public CategoryRequest() { }

        /// <summary>
        /// Initializes a new instance of the CategoryRequest class.
        /// </summary>
        public CategoryRequest(int? categoryid = default(int?), string categoryname = default(string), string isactive = default(string))
        {
            Categoryid = categoryid;
            Categoryname = categoryname;
            Isactive = isactive;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryid")]
        public int? Categoryid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryname")]
        public string Categoryname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }

    }
}
