// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class CategoryRequest
    {
        /// <summary>
        ///     Initializes a new instance of the CategoryRequest class.
        /// </summary>
        public CategoryRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the CategoryRequest class.
        /// </summary>
        public CategoryRequest(int? categoryid = default, string categoryname = default,
            string isactive = default)
        {
            Categoryid = categoryid;
            Categoryname = categoryname;
            Isactive = isactive;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryid")]
        public int? Categoryid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryname")]
        public string Categoryname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }
    }
}