// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public partial class CumulativeActivityReport
    {
        /// <summary>
        /// Initializes a new instance of the CumulativeActivityReport class.
        /// </summary>
        public CumulativeActivityReport()
        {
        }

        /// <summary>
        /// Initializes a new instance of the CumulativeActivityReport class.
        /// </summary>
        public CumulativeActivityReport(string capturedDate = default(string), string dailySum = default(string),
            string email = default(string), string executableName = default(string),
            string monthlySum = default(string), string usedTime = default(string), string yearlySum = default(string))
        {
            CapturedDate = capturedDate;
            DailySum = dailySum;
            Email = email;
            ExecutableName = executableName;
            MonthlySum = monthlySum;
            UsedTime = usedTime;
            YearlySum = yearlySum;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capturedDate")]
        public string CapturedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dailySum")]
        public string DailySum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executable_name")]
        public string ExecutableName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monthlySum")]
        public string MonthlySum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "used_time")]
        public string UsedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "yearlySum")]
        public string YearlySum { get; set; }
    }
}