// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class CumulativeReportResponse
    {
        /// <summary>
        ///     Initializes a new instance of the CumulativeReportResponse class.
        /// </summary>
        public CumulativeReportResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the CumulativeReportResponse class.
        /// </summary>
        public CumulativeReportResponse(
            IList<CumulativeActivityReport> activityReports = default)
        {
            ActivityReports = activityReports;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityReports")]
        public IList<CumulativeActivityReport> ActivityReports { get; set; }
    }
}