// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class MeasurementTypeResponse
    {
        /// <summary>
        ///     Initializes a new instance of the MeasurementTypeResponse class.
        /// </summary>
        public MeasurementTypeResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the MeasurementTypeResponse class.
        /// </summary>
        public MeasurementTypeResponse(string createdby = default, DateTime? creationdate = default,
            string description = default, string isactive = default, string label = default,
            DateTime? lastupdate = default, int? measurementtypeid = default,
            string operation = default, double? scale = default, string updateby = default,
            double? weight = default)
        {
            Createdby = createdby;
            Creationdate = creationdate;
            Description = description;
            Isactive = isactive;
            Label = label;
            Lastupdate = lastupdate;
            Measurementtypeid = measurementtypeid;
            Operation = operation;
            Scale = scale;
            Updateby = updateby;
            Weight = weight;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdby")]
        public string Createdby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creationdate")]
        public DateTime? Creationdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastupdate")]
        public DateTime? Lastupdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "measurementtypeid")]
        public int? Measurementtypeid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scale")]
        public double? Scale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateby")]
        public string Updateby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double? Weight { get; set; }
    }
}