// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MeasurementReport
    {
        /// <summary>
        /// Initializes a new instance of the MeasurementReport class.
        /// </summary>
        public MeasurementReport() { }

        /// <summary>
        /// Initializes a new instance of the MeasurementReport class.
        /// </summary>
        public MeasurementReport(string alternativeLabel = default(string), DateTime? capturedDate = default(DateTime?), string measurementTypeId = default(string), string value = default(string))
        {
            AlternativeLabel = alternativeLabel;
            CapturedDate = capturedDate;
            MeasurementTypeId = measurementTypeId;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alternativeLabel")]
        public string AlternativeLabel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capturedDate")]
        public DateTime? CapturedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "measurementTypeId")]
        public string MeasurementTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
