// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class MeasurementReport
    {
        /// <summary>
        ///     Initializes a new instance of the MeasurementReport class.
        /// </summary>
        public MeasurementReport()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the MeasurementReport class.
        /// </summary>
        public MeasurementReport(string alternativeLabel = default, DateTime? capturedDate = default,
            string measurementTypeId = default, string value = default)
        {
            AlternativeLabel = alternativeLabel;
            CapturedDate = capturedDate;
            MeasurementTypeId = measurementTypeId;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alternativeLabel")]
        public string AlternativeLabel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capturedDate")]
        public DateTime? CapturedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "measurementTypeId")]
        public string MeasurementTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }
    }
}