// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public partial class ProcessReport
    {
        /// <summary>
        /// Initializes a new instance of the ProcessReport class.
        /// </summary>
        public ProcessReport()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ProcessReport class.
        /// </summary>
        public ProcessReport(DateTime? collectedTime = default(DateTime?), string ipAddress = default(string),
            string macAddress = default(string),
            IList<MeasurementReport> measurementReportList = default(IList<MeasurementReport>),
            string osversion = default(string), string pid = default(string), string processName = default(string),
            string userID = default(string))
        {
            CollectedTime = collectedTime;
            IpAddress = ipAddress;
            MacAddress = macAddress;
            MeasurementReportList = measurementReportList;
            Osversion = osversion;
            Pid = pid;
            ProcessName = processName;
            UserID = userID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collectedTime")]
        public DateTime? CollectedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ip_address")]
        public string IpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mac_address")]
        public string MacAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "measurementReportList")]
        public IList<MeasurementReport> MeasurementReportList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "osversion")]
        public string Osversion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pid")]
        public string Pid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processName")]
        public string ProcessName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userID")]
        public string UserID { get; set; }
    }
}