// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public class ProjectResponse
    {
        /// <summary>
        ///     Initializes a new instance of the ProjectResponse class.
        /// </summary>
        public ProjectResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the ProjectResponse class.
        /// </summary>
        public ProjectResponse(string isActive = default, string name = default,
            int? projectID = default)
        {
            IsActive = isActive;
            Name = name;
            ProjectID = projectID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public string IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectID")]
        public int? ProjectID { get; set; }
    }
}