// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace APIClient.InnoMetricClient.Models
{
    public partial class ProjectRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProjectRequest class.
        /// </summary>
        public ProjectRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ProjectRequest class.
        /// </summary>
        public ProjectRequest(string isActive = default(string), string name = default(string),
            int? projectID = default(int?))
        {
            IsActive = isActive;
            Name = name;
            ProjectID = projectID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public string IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectID")]
        public int? ProjectID { get; set; }
    }
}