// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UserRequest
    {
        /// <summary>
        /// Initializes a new instance of the UserRequest class.
        /// </summary>
        public UserRequest() { }

        /// <summary>
        /// Initializes a new instance of the UserRequest class.
        /// </summary>
        public UserRequest(DateTime? confirmedAt = default(DateTime?), string email = default(string), string isactive = default(string), string name = default(string), string password = default(string), string surname = default(string))
        {
            ConfirmedAt = confirmedAt;
            Email = email;
            Isactive = isactive;
            Name = name;
            Password = password;
            Surname = surname;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "confirmed_at")]
        public DateTime? ConfirmedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "surname")]
        public string Surname { get; set; }

    }
}
