// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AppCategoryResponse
    {
        /// <summary>
        /// Initializes a new instance of the AppCategoryResponse class.
        /// </summary>
        public AppCategoryResponse() { }

        /// <summary>
        /// Initializes a new instance of the AppCategoryResponse class.
        /// </summary>
        public AppCategoryResponse(int? appid = default(int?), string appname = default(string), int? categoryid = default(int?), string createdby = default(string), DateTime? creationdate = default(DateTime?), string isactive = default(string), DateTime? lastupdate = default(DateTime?), string updateby = default(string))
        {
            Appid = appid;
            Appname = appname;
            Categoryid = categoryid;
            Createdby = createdby;
            Creationdate = creationdate;
            Isactive = isactive;
            Lastupdate = lastupdate;
            Updateby = updateby;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appid")]
        public int? Appid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appname")]
        public string Appname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryid")]
        public int? Categoryid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdby")]
        public string Createdby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creationdate")]
        public DateTime? Creationdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isactive")]
        public string Isactive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastupdate")]
        public DateTime? Lastupdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateby")]
        public string Updateby { get; set; }

    }
}
