// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InnoMetric.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ProcessReport
    {
        /// <summary>
        /// Initializes a new instance of the ProcessReport class.
        /// </summary>
        public ProcessReport() { }

        /// <summary>
        /// Initializes a new instance of the ProcessReport class.
        /// </summary>
        public ProcessReport(string ipAddress = default(string), string macAddress = default(string), IList<MeasurementReport> measurementReportList = default(IList<MeasurementReport>), string processName = default(string), string userID = default(string))
        {
            IpAddress = ipAddress;
            MacAddress = macAddress;
            MeasurementReportList = measurementReportList;
            ProcessName = processName;
            UserID = userID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ip_address")]
        public string IpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mac_address")]
        public string MacAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "measurementReportList")]
        public IList<MeasurementReport> MeasurementReportList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processName")]
        public string ProcessName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userID")]
        public string UserID { get; set; }

    }
}
